apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml

images:
- name: 139286777794.dkr.ecr.eu-north-1.amazonaws.com/gitops
  newTag: 809f684ea5e9bb72b9b507a01cc23b72b6a62948
- name: frontend
  newName: 139286777794.dkr.ecr.eu-north-1.amazonaws.com/gitops
  newTag: 809f684ea5e9bb72b9b507a01cc23b72b6a62948
- name: guestbook
  newName: gitops
  newTag: new
