apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml

images:
- name: /
- name: 139286777794.dkr.ecr.eu-north-1.amazonaws.com/gitops
  newName: 139286777794.dkr.ecr.eu-north-1.amazonaws.com/gitops
  newTag: ff0d8a090a60a0487949de89ee6f9afc006809ac
- name: frontend
  newName: guestbook
  newTag: 3fa38b9d2acb82a6e567c5935d1037a1339e4f1d
- name: guestbook
  newName: guestbook
  newTag: new
